import { UserProfileProps } from "@/types/user"

export const authUser : UserProfileProps = {
    name : 'Wilson Walton',
    username : 'wilson_walton',
    profile_picture : '/person.jpg',
    cover_photo : '/people/bima_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : false,
    postTotal : 10,
    joinedAt : '32 July 2021',
}

export const initialUsers = [
  {
    name : 'Bima PN',
    username : 'bimapn',
    profile_picture : '/people/bima_pn.jpg',
    cover_photo : '/people/bima_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Fabian Azhar',
    username : 'fabian',
    profile_picture : '/people/fabian_azhar.png',
    cover_photo : '/people/fabian_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Caroline Konstnar',
    username : 'caroline_konstnar',
    profile_picture : '/people/caroline.webp',
    cover_photo : '/people/caroline_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Cristiano Ronaldo',
    username : 'cristiano',
    profile_picture : '/people/cristiano_ronaldo.jpg',
    cover_photo : '/people/cristiano_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Marshall Mathers',
    username : 'eminem',
    profile_picture : '/people/eminem.jpg',
    cover_photo : '/people/eminem_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Mike Tyson',
    username : 'mike_tyson',
    profile_picture : '/people/tyson.jpg',
    cover_photo : '/people/tyson_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
  {
    name : 'Richard Dawkins',
    username : 'richard_dawkins',
    profile_picture : '/people/dawkins.jpg',
    cover_photo : '/people/dawkins_cover.jpg',
    bio : 'Guzzling, Fiery, Matter, Pure, Latch, Renew, Glimmer, Foundation, Crisis, Geometric, Sail, Biggest, Clear, Thundering',
    followingTotal : 23,
    followerTotal : 621,
    isFollow : false,
    isVerified : true,
    postTotal : 10,
    joinedAt : '32 July 2021',
  },
]
