import type { Metadata } from "next";
import { Roboto, Lato, Open_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import DarkModeProvider from "@/components/providers/DarkModeProvider";
import 'react-loading-skeleton/dist/skeleton.css'
import ProgressbarProvider from "@/components/providers/ProgressbarProvider";

const roboto = Roboto({ 
  weight: ['400', '500', '700'],
  subsets: ['latin'] 
})
const open_s = Open_Sans({ 
  weight: ['400', '500', '700'],
  subsets: ['latin'] 
})
const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'] 
  })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={open_s.className}>
        <ProgressbarProvider>
          <DarkModeProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </DarkModeProvider>
        </ProgressbarProvider>
      </body>
    </html>
  );
}
